### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by zsnmwy** [Indexyz/steam_2018_summer_game#4]
`node dist/index.js`

```shell
[root@ubuntu-s-1vcpu-1gb-fra1-01 summer_game]# node dist/index.js
/opt/summer_game/node_modules/config/lib/config.js:1304
        throw Error(msg);
        ^

Error: Illegal key type for substitution map at : object
    at _substituteVars (/opt/summer_game/node_modules/config/lib/config.js:1304:15)
    at Config.util.substituteDeep (/opt/summer_game/node_modules/config/lib/config.js:1309:3)
    at /opt/summer_game/node_modules/config/lib/config.js:1329:43
    at Array.forEach (<anonymous>)
    at Config.util.getCustomEnvVars (/opt/summer_game/node_modules/config/lib/config.js:1325:12)
    at Config.util.loadFileConfigs (/opt/summer_game/node_modules/config/lib/config.js:770:28)
    at new Config (/opt/summer_game/node_modules/config/lib/config.js:135:27)
    at Object.<anonymous> (/opt/summer_game/node_modules/config/lib/config.js:1782:31)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
```

`npm run dev`

```shell
[root@ubuntu-s-1vcpu-1gb-fra1-01 summer_game]# npm run dev

> steam_2018_summer_game@1.0.0 dev /opt/summer_game
> ts-node src/index.ts


/opt/summer_game/node_modules/config/lib/config.js:1304
        throw Error(msg);
              ^
Error: Illegal key type for substitution map at : object
    at _substituteVars (/opt/summer_game/node_modules/config/lib/config.js:1304:15)
    at Config.util.substituteDeep (/opt/summer_game/node_modules/config/lib/config.js:1309:3)
    at /opt/summer_game/node_modules/config/lib/config.js:1329:43
    at Array.forEach (<anonymous>)
    at Config.util.getCustomEnvVars (/opt/summer_game/node_modules/config/lib/config.js:1325:12)
    at Config.util.loadFileConfigs (/opt/summer_game/node_modules/config/lib/config.js:770:28)
    at new Config (/opt/summer_game/node_modules/config/lib/config.js:135:27)
    at Object.<anonymous> (/opt/summer_game/node_modules/config/lib/config.js:1782:31)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! steam_2018_summer_game@1.0.0 dev: `ts-node src/index.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the steam_2018_summer_game@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-06-25T19_11_30_611Z-debug.log
[root@ubuntu-s-1vcpu-1gb-fra1-01 summer_game]# 
```

这个报错是在支持heroku之后才报的。
之前并没有报错。
我是不是碰到上了版本迭代...看你疯狂commit2333

**Comment by 5aaee9** [comment]
尝试更新到最新版本 
已在 8c014ff37bb671bbee93f5015bde2735cc8cd78d 修复
