### ISSUE TITLE
出现boos区和bug提交

### ISSUE THREAD

**Issue by Tang-DJ** [Indexyz/steam_2018_summer_game#8]
希望可以尽快更新

**Comment by 5aaee9** [comment]
知道了 等有 boss 的时候我再看看 现在貌似没 boss 了

**Comment by Tang-DJ** [comment]
脚本现在全部卡在荣耀2星球 请尝试修复一下
已定位错误 index.ts 
49行 更改为 const zones = planet.planets[0].zones
            .filter(item => !item.captured && item.top_clans)
即可修复错误

**Comment by Tang-DJ** [comment]
Boss room founded, joining
TypeError: Cannot read property 'getPlanetInfoRequest' of undefined
    at /Users/tangdaijia/program/study/steam_2018_summer_game/dist/index.js:40:47
    at Generator.next (<anonymous>)
    at fulfilled (/Users/tangdaijia/program/study/steam_2018_summer_game/dist/index.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:178:7)

**Comment by Tang-DJ** [comment]
TypeError: Cannot read property 'boss_hp' of undefined
    at SalienGame.<anonymous> (/root/summergame/dist/requests.js:139:76)
    at Generator.next (<anonymous>)
    at fulfilled (/root/summergame/dist/requests.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
中间打印的结构体太占位置，请取消一下
